// products.js
window.allProducts = [
  // Trang chủ (Bộ sưu tập đặc biệt)
  {id: 'TC1', name: 'Ánh Sao Khuya', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 100, image: 'test/BT_1.png'},
  {id: 'TC2', name: 'Giấc Mơ Hồng', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 110, image: 'test/BT_2.png'},
  {id: 'TC3', name: 'Tinh Hoa Phương Đông', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 120, image: 'test/DC_4.png'},
  {id: 'TC4', name: 'Vũ Khúc Ánh Sáng', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 130, image: 'test/ĐH_7.png'},
  {id: 'TC5', name: 'Mộng Mơ Nơi Xa', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 140, image: 'test/ĐH_8.png'},
  {id: 'TC6', name: 'Giọt Thủy Tinh', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 150, image: 'img/daychuyen/D9.png'},
  {id: 'TC7', name: 'Vầng Trăng Yêu Thương', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 160, image: 'test/vòng tay 2.png'},
  {id: 'TC8', name: 'Đóa Hồng Đêm', desc: 'Mô tả ngắn gọn về sản phẩm.', price: 170, image: 'test/Vòng tay.png'},
  // Vòng tay
  {id: 'VT1', name: 'Vòng Tay Vàng Hạnh Phúc', desc: 'Thiết kế sang trọng, tinh tế.', price: 100, image: 'img/vongtay/N2.png'},
  {id: 'VT2', name: 'Vòng Tay Vàng Kim Tuyến', desc: 'Thiết kế sang trọng, tinh tế.', price: 110, image: 'img/vongtay/N6.png'},
  {id: 'VT3', name: 'Vòng Tay Vàng Phúc Lộc', desc: 'Thiết kế sang trọng, tinh tế.', price: 120, image: 'img/vongtay/N11.png'},
  {id: 'VT4', name: 'Vòng Tay Vàng Mặt Trời', desc: 'Thiết kế sang trọng, tinh tế.', price: 130, image: 'img/vongtay/N19.png'},
  {id: 'VT5', name: 'Vòng Tay Bạc Dịu Dàng', desc: 'Thiết kế sang trọng, tinh tế.', price: 140, image: 'img/vongtay/N1.png'},
  {id: 'VT6', name: 'Vòng Tay Bạc Hoa Tuyết', desc: 'Thiết kế sang trọng, tinh tế.', price: 150, image: 'img/vongtay/N3.png'},
  {id: 'VT7', name: 'Vòng Tay Bạc Sắc Thu', desc: 'Thiết kế sang trọng, tinh tế.', price: 160, image: 'img/vongtay/N4.png'},
  {id: 'VT8', name: 'Vòng Tay Bạc Cánh Chim', desc: 'Thiết kế sang trọng, tinh tế.', price: 170, image: 'img/vongtay/N5.png'},
  {id: 'VT9', name: 'Vòng Tay Bạc Giọt Nắng', desc: 'Thiết kế sang trọng, tinh tế.', price: 180, image: 'img/vongtay/N7.png'},
  {id: 'VT10', name: 'Vòng Tay Bạc Bình Minh', desc: 'Thiết kế sang trọng, tinh tế.', price: 190, image: 'img/vongtay/N8.png'},
  {id: 'VT11', name: 'Vòng Tay Bạc Gợn Sóng', desc: 'Thiết kế sang trọng, tinh tế.', price: 200, image: 'img/vongtay/N9.png'},
  {id: 'VT12', name: 'Vòng Tay Bạc Trăng Non', desc: 'Thiết kế sang trọng, tinh tế.', price: 210, image: 'img/vongtay/N10.png'},
  {id: 'VT13', name: 'Vòng Tay Bạc Hoa Mộng', desc: 'Thiết kế sang trọng, tinh tế.', price: 220, image: 'img/vongtay/N12.png'},
  {id: 'VT14', name: 'Vòng Tay Bạc Nhẹ Bước', desc: 'Thiết kế sang trọng, tinh tế.', price: 230, image: 'img/vongtay/N13.png'},
  {id: 'VT15', name: 'Vòng Tay Bạc Sương Sớm', desc: 'Thiết kế sang trọng, tinh tế.', price: 240, image: 'img/vongtay/N14.png'},
  {id: 'VT16', name: 'Vòng Tay Bạc Gió Hạ', desc: 'Thiết kế sang trọng, tinh tế.', price: 250, image: 'img/vongtay/N15.png'},
  // Bông Tai
  {id: 'BT1', name: 'Bông Tai Vàng Mặt Trời', desc: 'Thiết kế sang trọng, tinh tế.', price: 100, image: 'img/bongtai/B1.png'},
  {id: 'BT2', name: 'Bông Tai Vàng Ánh Bình Minh', desc: 'Thiết kế sang trọng, tinh tế.', price: 110, image: 'img/bongtai/B3.png'},
  {id: 'BT3', name: 'Bông Tai Vàng Giọt Sáng', desc: 'Thiết kế sang trọng, tinh tế.', price: 120, image: 'img/bongtai/B5.png'},
  {id: 'BT4', name: 'Bông Tai Vàng Cát Vàng', desc: 'Thiết kế sang trọng, tinh tế.', price: 130, image: 'img/bongtai/B7.png'},
  {id: 'BT5', name: 'Bông Tai Bạc Trăng Sáng', desc: 'Thiết kế sang trọng, tinh tế.', price: 140, image: 'img/bongtai/B2.png'},
  {id: 'BT6', name: 'Bông Tai Bạc Giọt Mưa', desc: 'Thiết kế sang trọng, tinh tế.', price: 150, image: 'img/bongtai/B4.png'},
  {id: 'BT7', name: 'Bông Tai Bạc Sao Đêm', desc: 'Thiết kế sang trọng, tinh tế.', price: 160, image: 'img/bongtai/B6.png'},
  {id: 'BT8', name: 'Bông Tai Bạc Tuyết Nhẹ', desc: 'Thiết kế sang trọng, tinh tế.', price: 170, image: 'img/bongtai/B8.png'},
  {id: 'BT9', name: 'Bông Tai Bạc Ánh Sương', desc: 'Thiết kế sang trọng, tinh tế.', price: 180, image: 'img/bongtai/B9.png'},
  {id: 'BT10', name: 'Bông Tai Bạc Làn Gió', desc: 'Thiết kế sang trọng, tinh tế.', price: 190, image: 'img/bongtai/B10.png'},
  {id: 'BT11', name: 'Bông Tai Bạc Sóng Nhẹ', desc: 'Thiết kế sang trọng, tinh tế.', price: 200, image: 'img/bongtai/B12.png'},
  {id: 'BT12', name: 'Bông Tai Bạc Pha Lê', desc: 'Thiết kế sang trọng, tinh tế.', price: 210, image: 'img/bongtai/B13.png'},
  {id: 'BT13', name: 'Bông Tai Bạc Tinh Sương', desc: 'Thiết kế sang trọng, tinh tế.', price: 220, image: 'img/bongtai/B14.png'},
  {id: 'BT14', name: 'Bông Tai Bạc Hơi Thở', desc: 'Thiết kế sang trọng, tinh tế.', price: 230, image: 'img/bongtai/B15.png'},
  {id: 'BT15', name: 'Bông Tai Bạc Cánh Hoa', desc: 'Thiết kế sang trọng, tinh tế.', price: 240, image: 'img/bongtai/B16.png'},
  {id: 'BT16', name: 'Bông Tai Bạc Bình Yên', desc: 'Thiết kế sang trọng, tinh tế.', price: 250, image: 'img/bongtai/B17.png'},
  // Dây Chuyền
  {id: 'DC1', name: 'Dây Chuyền Vàng Ngọc Quý', desc: 'Thiết kế sang trọng, tinh tế.', price: 100, image: 'img/daychuyen/D2.png'},
  {id: 'DC2', name: 'Dây Chuyền Vàng Tỏa Sáng', desc: 'Phong cách cổ điển, nữ tính.', price: 200, image: 'img/daychuyen/D8.png'},
  {id: 'DC3', name: 'Dây Chuyền Vàng Ánh Dương', desc: 'Phong cách cổ điển, nữ tính.', price: 300, image: 'img/daychuyen/D10.png'},
  {id: 'DC4', name: 'Dây Chuyền Vàng Hoa Mai', desc: 'Phong cách cổ điển, nữ tính.', price: 400, image: 'img/daychuyen/D12.png'},
  {id: 'DC5', name: 'Dây Chuyền Bạc Lấp Lánh', desc: 'Phong cách cổ điển, nữ tính.', price: 500, image: 'img/daychuyen/D1.png'},
  {id: 'DC6', name: 'Dây Chuyền Bạc Thanh Khiết', desc: 'Phong cách cổ điển, nữ tính.', price: 600, image: 'img/daychuyen/D3.png'},
  {id: 'DC7', name: 'Dây Chuyền Bạc Sao Trời', desc: 'Phong cách cổ điển, nữ tính.', price: 700, image: 'img/daychuyen/D4.png'},
  {id: 'DC8', name: 'Dây Chuyền Bạc Nhẹ Nhàng', desc: 'Phong cách cổ điển, nữ tính.', price: 800, image: 'img/daychuyen/D5.png'},
  {id: 'DC9', name: 'Dây Chuyền Bạc Ánh Trăng', desc: 'Phong cách cổ điển, nữ tính.', price: 900, image: 'img/daychuyen/D6.png'},
  {id: 'DC10', name: 'Dây Chuyền Bạc Mộng Mơ', desc: 'Phong cách cổ điển, nữ tính.', price: 1000, image: 'img/daychuyen/D7.png'},
  {id: 'DC11', name: 'Dây Chuyền Bạc Tuyết Trắng', desc: 'Phong cách cổ điển, nữ tính.', price: 1100, image: 'img/daychuyen/D9.png'},
  {id: 'DC12', name: 'Dây Chuyền Bạc Lấp Lánh', desc: 'Phong cách cổ điển, nữ tính.', price: 1200, image: 'img/daychuyen/D11.png'},
  {id: 'DC13', name: 'Dây Chuyền Bạc Dòng Sông', desc: 'Phong cách cổ điển, nữ tính.', price: 1300, image: 'img/daychuyen/D13.png'},
  {id: 'DC14', name: 'Dây Chuyền Bạc Băng Tuyết', desc: 'Phong cách cổ điển, nữ tính.', price: 1400, image: 'img/daychuyen/D15.png'},
  {id: 'DC15', name: 'Dây Chuyền Bạc Dịu Êm', desc: 'Phong cách cổ điển, nữ tính.', price: 1500, image: 'img/daychuyen/D16.png'},
  {id: 'DC16', name: 'Dây Chuyền Bạc Thiên Nhiên', desc: 'Phong cách cổ điển, nữ tính.', price: 1600, image: 'img/daychuyen/D17.png'},
  // Đồng Hồ
  {id: 'DH1', name: 'Đồng Hồ Vàng Hoàng Gia', desc: 'Thiết kế sang trọng, tinh tế.', price: 105, image: 'img/dongho/Đ3.png'},
  {id: 'DH2', name: 'Đồng Hồ Vàng Ánh Kim', desc: 'Thiết kế sang trọng, tinh tế.', price: 110, image: 'img/dongho/Đ4.png'},
  {id: 'DH3', name: 'Đồng Hồ Vàng Vĩnh Hằng', desc: 'Thiết kế sang trọng, tinh tế.', price: 115, image: 'img/dongho/Đ5.png'},
  {id: 'DH4', name: 'Đồng Hồ Vàng Tỏa Nắng', desc: 'Thiết kế sang trọng, tinh tế.', price: 120, image: 'img/dongho/Đ6.png'},
  {id: 'DH5', name: 'Đồng Hồ Vàng Tinh Hoa', desc: 'Thiết kế sang trọng, tinh tế.', price: 125, image: 'img/dongho/Đ17.png'},
  {id: 'DH6', name: 'Đồng Hồ Vàng Lịch Lãm', desc: 'Thiết kế sang trọng, tinh tế.', price: 130, image: 'img/dongho/Đ18.png'},
  {id: 'DH7', name: 'Đồng Hồ Bạc Băng Giá', desc: 'Thiết kế sang trọng, tinh tế.', price: 135, image: 'img/dongho/Đ1.png'},
  {id: 'DH8', name: 'Đồng Hồ Bạc Tối Giản', desc: 'Thiết kế sang trọng, tinh tế.', price: 140, image: 'img/dongho/Đ2.png'},
  {id: 'DH9', name: 'Đồng Hồ Bạc Ánh Sáng', desc: 'Thiết kế sang trọng, tinh tế.', price: 145, image: 'img/dongho/Đ7.png'},
  {id: 'DH10', name: 'Đồng Hồ Bạc Sương Mai', desc: 'Thiết kế sang trọng, tinh tế.', price: 150, image: 'img/dongho/Đ8.png'},
  {id: 'DH11', name: 'Đồng Hồ Bạc Sao Rơi', desc: 'Thiết kế sang trọng, tinh tế.', price: 155, image: 'img/dongho/Đ9.png'},
  {id: 'DH12', name: 'Đồng Hồ Bạc Thanh Lịch', desc: 'Thiết kế sang trọng, tinh tế.', price: 160, image: 'img/dongho/Đ10.png'},
  {id: 'DH13', name: 'Đồng Hồ Bạc Năng Lượng', desc: 'Thiết kế sang trọng, tinh tế.', price: 165, image: 'img/dongho/Đ11.png'},
  {id: 'DH14', name: 'Đồng Hồ Bạc Tinh Tế', desc: 'Thiết kế sang trọng, tinh tế.', price: 170, image: 'img/dongho/Đ12.png'},
  {id: 'DH15', name: 'Đồng Hồ Bạc Thời Gian', desc: 'Thiết kế sang trọng, tinh tế.', price: 175, image: 'img/dongho/Đ13.png'},
  {id: 'DH16', name: 'Đồng Hồ Bạc Mặt Trăng', desc: 'Thiết kế sang trọng, tinh tế.', price: 180, image: 'img/dongho/Đ16.png'},
  // Nhẫn
  {id: 'N1', name: 'Nhẫn Vàng Ánh Dương', desc: 'Thiết kế sang trọng, tinh tế.', price: 100, image: 'img/nhan/N1.png'},
  {id: 'N2', name: 'Nhẫn Vàng Vĩnh Cửu', desc: 'Phong cách cổ điển, nữ tính.', price: 50, image: 'img/nhan/N3.png'},
  {id: 'N3', name: 'Nhẫn Vàng Hoa Nắng', desc: 'Phong cách cổ điển, nữ tính.', price: 70, image: 'img/nhan/N5.png'},
  {id: 'N4', name: 'Nhẫn Vàng Tâm An', desc: 'Phong cách cổ điển, nữ tính.', price: 60, image: 'img/nhan/N7.png'},
  {id: 'N5', name: 'Nhẫn Vàng Minh Châu', desc: 'Phong cách cổ điển, nữ tính.', price: 80, image: 'img/nhan/N8.png'},
  {id: 'N6', name: 'Nhẫn Vàng Phú Quý', desc: 'Phong cách cổ điển, nữ tính.', price: 90, image: 'img/nhan/N10.png'},
  {id: 'N7', name: 'Nhẫn Vàng Huy Hoàng', desc: 'Phong cách cổ điển, nữ tính.', price: 110, image: 'img/nhan/N13.png'},
  {id: 'N8', name: 'Nhẫn Vàng Ánh Kim', desc: 'Phong cách cổ điển, nữ tính.', price: 120, image: 'img/nhan/N15.png'},
  {id: 'N9', name: 'Nhẫn Bạc Trăng Non', desc: 'Phong cách cổ điển, nữ tính.', price: 130, image: 'img/nhan/N2.png'},
  {id: 'N10', name: 'Nhẫn Bạc Tinh Tú', desc: 'Phong cách cổ điển, nữ tính.', price: 140, image: 'img/nhan/N4.png'},
  {id: 'N11', name: 'Nhẫn Bạc Nhẹ Nhàng', desc: 'Phong cách cổ điển, nữ tính.', price: 150, image: 'img/nhan/N6.png'},
  {id: 'N12', name: 'Nhẫn Bạc Mộng Mơ', desc: 'Phong cách cổ điển, nữ tính.', price: 160, image: 'img/nhan/N9.png'},
  {id: 'N13', name: 'Nhẫn Bạc Thiên Hà', desc: 'Phong cách cổ điển, nữ tính.', price: 170, image: 'img/nhan/N11.png'},
  {id: 'N14', name: 'Nhẫn Bạc Gió Đông', desc: 'Phong cách cổ điển, nữ tính.', price: 180, image: 'img/nhan/N12.png'},
  {id: 'N15', name: 'Nhẫn Bạc Thanh Xuân', desc: 'Phong cách cổ điển, nữ tính.', price: 190, image: 'img/nhan/N14.png'},
  {id: 'N16', name: 'Nhẫn Bạc Ánh Trăng', desc: 'Phong cách cổ điển, nữ tính.', price: 200, image: 'img/nhan/N16.png'},
]; 